# ==========================================================
#                  ALPHAFETCH CONFIGURATION
# ==========================================================
# Altere para 'false' para ocultar o módulo ou 'true' para exibir.

show_os=true
show_kernel=true
show_uptime=true
show_shell=true
show_packages=true
show_wm=true
show_terminal=true

show_cpu=true
show_gpu=true
show_ram=true
show_disk=true
show_ip=true
show_music=true

show_theme=true
show_icons=true
show_cursor=true
show_font=true

# Ativa ou desativa o uso de Nerd Fonts (ícones)
use_nerd_fonts=true

# mude as cores (certifique de ver config.cpp pra ver quais disponiveis)
color_label=b_white
color_value=white